<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <title>Reya</title>
</head>
<body>
    <main>
        <form action="/news" method="get"></form>
        <section class="smallNav">
          <div class="container">
            <div class="row mt-3 mb-3">
              <div class="col-12-md-3 col-12-lg-4 col-12-xl-3 text-muted">

                  <a href="/index.html" class="text-reset"><small>Главная</small></a>
                  <small>></small>
                  <a href="/html/news.html" class="text-reset"><small>Новости</small></a>

              </div>         
              </div>
              <div class="col-4-md-3 col-4-lg-4 col-4-xl-3">
                <p class="fs-3 fw-weight-bold">Новости</p>
              </div>
            </div>
        </section>

<div class="container">
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <a href="/html/news/1.html"><img class="card-img-top" src="/static/images/8mart.jpg" width="100%" height="225" alt="Card image cap"></a>
              <rect width="100%" height="100%" fill="#55595c"></rect>
              <text x="45%" y="50%" fill="#eceeef" dy=".3em"></text>
              <div class="card-body">
                <p class="card-text">С праздником!</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">7 марта 2023</small>
              </div>
            </div>
          </div>
        </div>
        
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" src="/images/8mart.jpg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#55595c"></rect>
              <text x="45%" y="50%" fill="#eceeef" dy=".3em">img</text>
            </svg>

            <div class="card-body">
              <p class="card-text">Текст новости 2</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">7 марта 2023</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
              <title>Placeholder</title>
              <rect width="100%" height="100%" fill="#55595c"></rect>
              <text x="45%" y="50%" fill="#eceeef" dy=".3em">img</text>
            </svg>

            <div class="card-body">
              <p class="card-text">Текст новости 3</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">7 марта 2023</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<script src="/js/bootstrap.bundle.min.js"></script>
<script src="/js/header.js"></script>
<script src="/js/footer.js"></script>
    </main>
</body>
</html>